<?php

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Kontak extends CI_Controller
{
	function __construct()
	{
		parent::__construct();
		$this->load->model('Kontak_model');
	}

	public function index()
	{
		$this->load->view('Kontak/kontak_form');
	} 

	public function tambah()
	{
		$data=array(
			'action'			=>site_url('Kontak/tambah_aksi'),
			'date'				=>set_value('date'),
			'nama'				=>set_value('nama'),
			'hp'				=>set_value('hp'),
			'email'				=>set_value('email'),
			'service'			=>set_value('service'),
			'feed'				=>set_value('feed'),
			'id_contact'		=>set_value('id_contact')
		);
		$this->load->view('Kontak',$data);
	}

	function tambah_aksi()
	{
		$data=array(
			'date'			=>$this->input->post('date'),
			'nama'			=>$this->input->post('nama'),
			'hp'			=>$this->input->post('hp'),
			'email'			=>$this->input->post('email'),
			'service'		=>$this->input->post('service'),
			'feed'			=>$this->input->post('feed')
		);
		$this->Kontak_model->tambah_data($data);
		redirect(site_url('kontak'));
	}
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */