<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class LoginMember extends CI_Controller
{
 
	function __construct(){
		parent::__construct();		
		$this->load->model('Staff_model');
 
	}
 
	function index(){
		if($this->session->userdata('loginedmember') && $this->session->userdata('loginedmember') == true)
		{
			redirect('member');
		}
		
		if(!$this->input->post())
		{
			$this->load->view('loginmember');
		}
		else
		{
			$cek_login=$this->Staff_model->cek_login(
				$this->input->post('user'),
				$this->input->post('pass')
				
			);
			if(!empty($cek_login))
			{
				$this->session->set_userdata('loginedmember', true);
				$this->session->set_userdata('user', $cek_login->user);
				redirect("member");
			}
			else 
			{
				redirect("loginmember");
			}
		}
	}
 
	
 
	function logout(){
		$this->session->sess_destroy();
		redirect(base_url('/'));
	}

}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */